### ISSUE TITLE
Documentation is not clear on how to set the destination path

### ISSUE THREAD

**Issue by buzzware** [kr-g/pygitgrab#1]
I need to specify where the files will be put.
In the readme there is the line :
```
# optional destination folder given, defaults to 'repo_alias' (name of this section in the config file)
```
but it has no key=value example directly under it

Nothing I tried worked.

I gave up trying to figure it out and decided not to use the tool, but I might in the future if this is resolved.

**Comment by kr-g** [comment]
not a bug. 
refer to sample (README.md under "pygg.cfg structure") 
use comma "," to specify different dest folder

**Comment by buzzware** [comment]
So do I use :

pull_alias="*.py", "my/destination/path" 

?

What does the "*.py" do? can I use just "*"  ?

All I want to do is set the destination. How about just :

destination="my/destination/path"

?

**Comment by kr-g** [comment]
hello gary,
i dont know what exactly is required. 
and i cant provide that kind of support here (this is here for bugs, it is not a tutorial).
the pattern matching is done with python glob. so semantics is the same.
just try the samples, and change then accordigly.

**Comment by kr-g** [comment]
##todo 
add python glob note to readme
